version: "3.8"

services:
  org-project-app:
    container_name: org-project-app
    restart: always
    environment:
      APP_PORT: ${API_PORT}
      API_HOST: ${API_HOST}
    build:
      context: ./api
      dockerfile: org-project.Dockerfile
      args:
        APP_PORT: ${APP_PORT}
#    ports: #uncomment both lines in case of util
#      - 8080:${API_PORT}
    networks:
      - org-project

  org-project-duckdns:
    container_name: org-project-duckdns
    restart: always
    image: ghcr.io/linuxserver/duckdns
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      SUBDOMAINS: ${SUBDOMAINS}
      DUCKDNS_TOKEN: ${DUCKDNS_TOKEN}
      LOG_FILE: ${LOG_FILE}
    networks:
      - org-project

networks:
  org-project:
    name: org-project
